#' Conveniently query a subset of a matrix
#'
#' Convenience function to extract a pixel and its neighbourhood from matrices, e.g. to query raster maps.
#'
#' @param map matrix
#' @param out Center of the matrix to be extracted
#' @param radius Radius of the matrix to be extracted
#'
#' @details
#' The function can be used to find a catchment outlet using a drainage area map generated by \code{atb}, when the coordinates are approximately known (for instance from the location of a discharge station). These coordinates can then be used by \code{subcatch}. However, note that \code{atb} uses a multiple direction flow algorithm, while \code{subcatch} uses single flow. Therefore, the drainage area for a pixel calculated by \code{atb} is likely to differ from the catchment area identified by \code{subcatch}.
#'
#' @return Square matrix of size (radius * 2 + 1)
#'
#' @references See \url{https://github.com/ICHydro/topmodel} for examples.
#'
#' @author Wouter Buytaert, Imperial College London
#'
#' @seealso \code{\link{subcatch}}
#'
#' @export
outlet <- function(map, out, radius = 2) {
  ## TODO: plot this as values with coordinates

  i <- out[1]
  j <- out[2]

  return(map[(i - radius):(i + radius), (j - radius):(j + radius)])
}
