#' Identification of rivers in a digital elevation model
#'
#' This function identifies river headwater cells based on threshold
#' values in a topographic index and accumulated area river (generated
#' using \code{topidx}. Rivers are then traced downslope using a single flow algorithm.
#'
#' @param DEM A matrix representing a digital elevation model [m] with equally sized pixels and equal NS and EW resolution
#' @param atb Matrix with topographic index values generated by \code{topidx}
#' @param area Matrix with drainage area values generated by \code{topidx}
#' @param res Resolution of the digital elevation model (m)
#' @param thatb A topographic index threshold for headwater cells
#' @param tharea A drainage threshold for headwater cells
#'
#' @details
#' Cells that exceed thatb or tharea in the respective maps are identified as headwater cells. The routine then traces down rivers from these cells based on a D8 algorithm and calculates the distance towards the outlet. Outlets are recognized by sinks, map borders or excluded areas (NA). The \code{subcatch} function can be used to set areas outside the target catchment to NA.
#'
#' @return A matrix of the same size as DEM.
#'
#' @references See \url{https://github.com/ICHydro/topmodel} for examples.
#'
#' @author Wouter Buytaert, Imperial College London, based on an implementation from the
#' Hydrology Group of Lancaster University
#'
#' @seealso \code{\link{subcatch}}, \code{\link{topidx}}
#'
#' @export
river <- function(DEM, atb, area, res, thatb, tharea) {
  ## data preparation
  stopifnot(is(DEM, "matrix"), is(atb, "matrix"), is(area, "matrix"))

  if (min(as.vector(DEM[!is.na(DEM)])) < -9000) {
    stop("DEM contains unrealistic values (< -9000)")
  }

  if (min(as.vector(atb[!is.na(atb)])) < -9000) {
    stop("Topographic index map contains unrealistic values (< -9000)")
  }

  if (min(as.vector(area[!is.na(area)])) < -9000) {
    stop("Cumulative area map contains unrealistic values (< -9000)")
  }

  DEM[is.na(DEM)] <- -9999
  atb[is.na(atb)] <- -9999
  area[is.na(area)] <- -9999

  nrow <- dim(DEM)[1]
  ncol <- dim(DEM)[2]

  ## calling the function
  result <- .C(
    "findrivers",
    PACKAGE = "topmodel",
    as.double(DEM),
    as.double(atb),
    as.double(area),
    result = double(nrow * ncol),
    as.integer(nrow),
    as.integer(ncol),
    as.double(res),
    as.double(thatb),
    as.double(tharea)
  )$result

  ## formatting the results

  result[result < 0] <- NA
  result <- matrix(result, nrow = nrow)

  return(result)
}
